# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ecobatestservice:
    image: ecb-test-service
    container_name: test-service
    build:
      context: .
      dockerfile: Ecoba.TestService/Dockerfile
    environment:
      - ServiceConfig__serviceDiscoveryAddress=http://192.168.0.172:8500
      - ServiceConfig__serviceAddress=http://test-service
      - ServiceConfig__serviceName=test-service
      - ServiceConfig__serviceId=4
