#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Ecoba.IdentityService/Ecoba.IdentityService.csproj", "Ecoba.IdentityService/"]
COPY ["Ecoba.BasePlugin/Ecoba.BasePlugin.csproj", "Ecoba.BasePlugin/"]
COPY ["Ecoba.TestService/Ecoba.TestService.csproj", "Ecoba.TestService/"]
RUN dotnet restore "Ecoba.IdentityService/Ecoba.IdentityService.csproj"
RUN dotnet restore "Ecoba.BasePlugin/Ecoba.BasePlugin.csproj"
RUN dotnet restore "Ecoba.TestService/Ecoba.TestService.csproj"
COPY . .
WORKDIR "/src/Ecoba.TestService"
RUN dotnet build "Ecoba.TestService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Ecoba.TestService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Ecoba.TestService.dll"]
