@approveToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ii0xMDAwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiQXBwcm92YWxARWNvYmF2aWV0bmFtLmNvbS52biIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJBcHByb3ZhbCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlZpZXdlciIsImV4cCI6MTY1MjE0NTgwMywiaXNzIjoiaHR0cHM6Ly9lY29iYS5jb20udm4vIiwiYXVkIjoiaHR0cHM6Ly9lY29iYS5jb20udm4vIn0.g_NvJW0bUpsMQV9VOmrcRHy6-A3gY-IJtCjVyqxdcl0
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjE5ODMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0cmFuZHVjaG9hbmcxQEVjb2JhdmlldG5hbS5jb20udm4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMTk4My4gVHLhuqduIMSQ4bupYyBIb8OgbmciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJWaWV3ZXIiLCJleHAiOjE2NTIxNDkzMzYsImlzcyI6Imh0dHBzOi8vZWNvYmEuY29tLnZuLyIsImF1ZCI6Imh0dHBzOi8vZWNvYmEuY29tLnZuLyJ9.pbx-vJb-6cyLdxLrkMMDsGX77qOX61pLfo0ZNSH_ccs



###
GET http://localhost:5001/api/v1/t/test/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjE5ODMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0cmFuZHVjaG9hbmcxQEVjb2JhdmlldG5hbS5jb20udm4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMTk4My4gVHLhuqduIMSQ4bupYyBIb8OgbmciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJWaWV3ZXIiLCJleHAiOjE2NTIxMzQ3NzEsImlzcyI6Imh0dHBzOi8vZWNvYmEuY29tLnZuLyIsImF1ZCI6Imh0dHBzOi8vZWNvYmEuY29tLnZuLyJ9.AIdRi1y5FRUD1WtnVAzMNzaA4UHS44HRHXhy6U34F-s




###
GET http://localhost:5001/api/v1/t/users/CheckPermission
Content-Type: application/json
Authorization: Bearer {{userToken}}